name: sengped_flutter_profile
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  device_preview: ^1.1.0
  url_launcher: ^6.2.1
  google_fonts: ^6.1.0
  flex_color_scheme: ^7.3.1
  responsive_sizer: ^3.2.0
  provider: ^6.1.1
  shimmer: ^3.0.0
  flutter_easyloading: ^3.0.5
  flutter_svg: ^2.0.9
  dio: ^5.3.3
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  timelines: ^0.1.0
  
  another_flushbar: ^1.12.30
  device_frame: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  #
  # flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/abstract.png
    - assets/images/layered-waves-haikei.png
    - assets/images/layered-waves-haikei.svg
    - assets/images/phone-call.png
    - assets/images/plum-plate.png
    - assets/images/icons/skills/
    - assets/images/icons/works/

    - assets/images/icons/
    - assets/images/cert/
    - assets/images/icons/briefcase-outline.svg
    - assets/images/icons/code-slash-outline.svg
    - assets/images/icons/newspaper-outline.svg
    - assets/images/icons/person-outline.svg
    - assets/images/icons/information-circle-outline.svg
    - assets/images/icons/mail-open-outline.svg
    - assets/images/icons/logo-linkedin.svg
    - assets/images/icons/business-outline.svg
    - assets/images/icons/navigate-outline.svg
    - assets/images/icons/trophy-outline.svg

    - assets/json/profile.json
    - assets/json/skills.json

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
